opp:
    name: opp

adj:
    name: adj

Oa:
    name: Oa 

Ob:
    name: Ob 

W:
    name: W

pJ:
    name: pJ

pN:
    name: pN

M:
    name: M

Ka:
    name: Ka 

Kb:
    name: Kb 

Ba:
    name: Ba 

Bb:
    name: Bb 

Ca:
    name: Ca 

Cb:
    name: Cb 

Da:
    name: Da 

Db:
    name: Db 

Pa:
    name: Pa 

Pb:
    name: Pb 

Q:
    name: Q

X:
    name: X

Sa:
    name: Sa 

Sb:
    name: Sb 
