A+1:
    name: A+1
    imageAlg: U R U' R'
A+2:
    name: A+2
A+3:
    name: A+3
A+4:
    name: A+4
A+5:
    name: A+5
A+6:
    name: A+6
A+7:
    name: A+7
A+8:
    name: A+8
A-1:
    name: A-1
A-2:
    name: A-2
A-3:
    name: A-3
A-4:
    name: A-4
A-5:
    name: A-5
A-6:
    name: A-6
A-7:
    name: A-7
A-8:
    name: A-8
B-1:
    name: B-1
B-2:
    name: B-2
B-3:
    name: B-3
B-4:
    name: B-4
B-5:
    name: B-5
B-6:
    name: B-6
B-7:
    name: B-7
B-8:
    name: B-8
B+1:
    name: B+1
B+2:
    name: B+2
B+3:
    name: B+3
B+4:
    name: B+4
B+5:
    name: B+5
B+6:
    name: B+6
B+7:
    name: B+7
B+8:
    name: B+8
W+1:
    name: W+1
W+2:
    name: W+2
W+3:
    name: W+3
W+4:
    name: W+4
W+5:
    name: W+5
W+6:
    name: W+6
W+7:
    name: W+7
W+8:
    name: W+8
W-1:
    name: W-1
W-2:
    name: W-2
W-3:
    name: W-3
W-4:
    name: W-4
W-5:
    name: W-5
W-6:
    name: W-6
W-7:
    name: W-7
W-8:
    name: W-8
M+1:
    name: M+1
M+2:
    name: M+2
M+3:
    name: M+3
M+4:
    name: M+4
M+5:
    name: M+5
M+6:
    name: M+6
M+7:
    name: M+7
M+8:
    name: M+8
M-1:
    name: M-1
M-2:
    name: M-2
M-3:
    name: M-3
M-4:
    name: M-4
M-5:
    name: M-5
M-6:
    name: M-6
M-7:
    name: M-7
M-8:
    name: M-8
R-1:
    name: R-1
R-2:
    name: R-2
R-3:
    name: R-3
R-4:
    name: R-4
R-5:
    name: R-5
R-6:
    name: R-6
R-7:
    name: R-7
R-8:
    name: R-8
R+1:
    name: R+1
R+2:
    name: R+2
R+3:
    name: R+3
R+4:
    name: R+4
R+5:
    name: R+5
R+6:
    name: R+6
R+7:
    name: R+7
R+8:
    name: R+8
X-1:
    name: X-1
X-2:
    name: X-2
X-3:
    name: X-3
X-4:
    name: X-4
X-5:
    name: X-5
X-6:
    name: X-6
X-7:
    name: X-7
X-8:
    name: X-8
X+1:
    name: X+1
X+2:
    name: X+2
X+3:
    name: X+3
X+4:
    name: X+4
X+5:
    name: X+5
X+6:
    name: X+6
X+7:
    name: X+7
X+8:
    name: X+8
K-1:
    name: K-1
K-2:
    name: K-2
K-3:
    name: K-3
K-4:
    name: K-4
K-5:
    name: K-5
K-6:
    name: K-6
K-7:
    name: K-7
K-8:
    name: K-8
K+1:
    name: K+1
K+2:
    name: K+2
K+3:
    name: K+3
K+4:
    name: K+4
K+5:
    name: K+5
K+6:
    name: K+6
K+7:
    name: K+7
K+8:
    name: K+8
I+1:
    name: I+1
I+2:
    name: I+2
I+3:
    name: I+3
I+4:
    name: I+4
I+5:
    name: I+5
I+6:
    name: I+6
I+7:
    name: I+7
I+8:
    name: I+8
I-1:
    name: I-1
I-2:
    name: I-2
I-3:
    name: I-3
I-4:
    name: I-4
I-5:
    name: I-5
I-6:
    name: I-6
I-7:
    name: I-7
I-8:
    name: I-8
H+1:
    name: H+1
H+2:
    name: H+2
H+3:
    name: H+3
H+4:
    name: H+4
H+5:
    name: H+5
H+6:
    name: H+6
H+7:
    name: H+7
H+8:
    name: H+8
H-1:
    name: H-1
H-2:
    name: H-2
H-3:
    name: H-3
H-4:
    name: H-4
H-5:
    name: H-5
H-6:
    name: H-6
H-7:
    name: H-7
H-8:
    name: H-8
Q+1:
    name: Q+1
Q+2:
    name: Q+2
Q+3:
    name: Q+3
Q+4:
    name: Q+4
Q+5:
    name: Q+5
Q+6:
    name: Q+6
Q+7:
    name: Q+7
Q+8:
    name: Q+8
Q-1:
    name: Q-1
Q-2:
    name: Q-2
Q-3:
    name: Q-3
Q-4:
    name: Q-4
Q-5:
    name: Q-5
Q-6:
    name: Q-6
Q-7:
    name: Q-7
Q-8:
    name: Q-8
P+1:
    name: P+1
P+2:
    name: P+2
P+3:
    name: P+3
P+4:
    name: P+4
P+5:
    name: P+5
P+6:
    name: P+6
P+7:
    name: P+7
P+8:
    name: P+8
P-1:
    name: P-1
P-2:
    name: P-2
P-3:
    name: P-3
P-4:
    name: P-4
P-5:
    name: P-5
P-6:
    name: P-6
P-7:
    name: P-7
P-8:
    name: P-8
G+1:
    name: G+1
G+2:
    name: G+2
G+3:
    name: G+3
G+4:
    name: G+4
G+5:
    name: G+5
G+6:
    name: G+6
G+7:
    name: G+7
G+8:
    name: G+8
G-1:
    name: G-1
G-2:
    name: G-2
G-3:
    name: G-3
G-4:
    name: G-4
G-5:
    name: G-5
G-6:
    name: G-6
G-7:
    name: G-7
G-8:
    name: G-8
E-1:
    name: E-1
E-2:
    name: E-2
E-3:
    name: E-3
E-4:
    name: E-4
E-5:
    name: E-5
E-6:
    name: E-6
E-7:
    name: E-7
E-8:
    name: E-8
E+1:
    name: E+1
E+2:
    name: E+2
E+3:
    name: E+3
E+4:
    name: E+4
E+5:
    name: E+5
E+6:
    name: E+6
E+7:
    name: E+7
E+8:
    name: E+8
J+1:
    name: J+1
J+2:
    name: J+2
J+3:
    name: J+3
J+4:
    name: J+4
J+5:
    name: J+5
J+6:
    name: J+6
J+7:
    name: J+7
J+8:
    name: J+8
L-1:
    name: L-1
L-2:
    name: L-2
L-3:
    name: L-3
L-4:
    name: L-4
L-5:
    name: L-5
L-6:
    name: L-6
L-7:
    name: L-7
L-8:
    name: L-8
L+1:
    name: L+1
L+2:
    name: L+2
L+3:
    name: L+3
L+4:
    name: L+4
L+5:
    name: L+5
L+6:
    name: L+6
L+7:
    name: L+7
L+8:
    name: L+8
J-1:
    name: J-1
J-2:
    name: J-2
J-3:
    name: J-3
J-4:
    name: J-4
J-5:
    name: J-5
J-6:
    name: J-6
J-7:
    name: J-7
J-8:
    name: J-8
T1: 
    name: T1
T2: 
    name: T2
T3: 
    name: T3
T4: 
    name: T4
T5: 
    name: T5
T6: 
    name: T6
T7: 
    name: T7
T8: 
    name: T8
S1: 
    name: S1
S2: 
    name: S2
S3: 
    name: S3
S4: 
    name: S4
S5: 
    name: S5
S6: 
    name: S6
S7: 
    name: S7
S8: 
    name: S8
U+1:
    name: U+1
U+2:
    name: U+2
U+3:
    name: U+3
U+4:
    name: U+4
U+5:
    name: U+5
U+6:
    name: U+6
U+7:
    name: U+7
U+8:
    name: U+8
U-1:
    name: U-1
U-2:
    name: U-2
U-3:
    name: U-3
U-4:
    name: U-4
U-5:
    name: U-5
U-6:
    name: U-6
U-7:
    name: U-7
U-8:
    name: U-8
V+1:
    name: V+1
V+2:
    name: V+2
V+3:
    name: V+3
V+4:
    name: V+4
V+5:
    name: V+5
V+6:
    name: V+6
V+7:
    name: V+7
V+8:
    name: V+8
V-1:
    name: V-1
V-2:
    name: V-2
V-3:
    name: V-3
V-4:
    name: V-4
V-5:
    name: V-5
V-6:
    name: V-6
V-7:
    name: V-7
V-8:
    name: V-8
F1: 
    name: F1
F2: 
    name: F2
D+1:
    name: D+1
D+2:
    name: D+2
D+3:
    name: D+3
D+4:
    name: D+4
D-1:
    name: D-1
D-2:
    name: D-2
D-3:
    name: D-3
D-4:
    name: D-4
C+1:
    name: C+1
C+2:
    name: C+2
C-1:
    name: C-1
C-2:
    name: C-2